### ISSUE TITLE
Nuxt Warning

### ISSUE THREAD

**Issue by stevepop** [laraveluk/website-v2#3]
@AidanLaycock  When running `yarn dev` there is a warning displayed; `WARN  Using <NuxtLayout> inside app.vue will cause unwanted layout shifting in your application. Consider removing <NuxtLayout> from app.vue and using it in your pages.`.  Perhaps you can look into this? Thanks!

**Comment by AidanLaycock** [comment]
@stevepop - This should hopefully be resolved by an upsteam Vue issue (https://github.com/nuxt/nuxt/issues/15240). As this is the documented way of using NuxtLayout in the official docs.

Hopefully the Vue issue will be resolved soon as there has been some movement on it recently.

**Comment by stevepop** [comment]
@AidanLaycock Thanks for the update👍🏿
